# 实验数据及配置
std: [1, 1, 1, 1, 1, 1]  # 默认 std 向量

files: '20251127/20251127_173203_57.txt'
TSfilename: '20251127/WU1127.txt'
IMU_file: '20251127/MT_07782A2B_012-001.txt'
idx1: 1363
idx2: 1468
t0_TS: 17.3
t0_IMU: 8.66